server.port: 8080

spring.datasource.url: jdbc:mysql://mysql/review-db

spring.rabbitmq.host: rabbitmq

spring.cloud.stream.kafka.binder.brokers: kafka

eureka.client.serviceUrl.defaultZone: http://eureka:8761/eureka/
